---
- hosts: logger
  roles:
    - logger
  tags: logger

- hosts: dc
  roles:
    - dc
    - common
  tags: dc

- hosts: wef
  roles:
    - wef
    - common
  tags: wef

- hosts: database
  roles:
    - database
    - common
  tags: database

#- hosts: web
#  roles:
#    - logger
#  tags: web  

- hosts: exchange
  roles:
    - exchange
    - common
  tags: exchange

- hosts: win10
  roles:
    - win10
    - common
  tags: win10

- hosts: secret
  roles:
    - secret
    - common
  tags: secret