---

logger:
  hosts:
    192.168.2.117:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_port: 22
      ansible_connection: ssh
      ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'

dc:
  hosts:
    192.168.2.110:

wef:
  hosts:
    192.168.2.111:

win10:
  hosts:
    192.168.2.109:
