---

- name: Hostname -> SECRET
  win_hostname:
    name: secret
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required


# This needs to be made idempodent
- name: Set HostOnly DNS Address
  win_shell: "$adapter = (get-netadapter | where {$_.MacAddress -eq '00-50-56-a3-b7-c4'}).Name; Set-DnsClientServerAddress -InterfaceAlias $adapter -ServerAddresses 192.168.38.102,8.8.8.8"

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Check if existing DetectionLab directory
  win_stat:
    path: 'C:\DetectionLab'
  register: dir

- name: "Ansible Create directory if not exists"
  ansible.windows.win_file:
    path: C:\DetectionLab
    state: directory
  when: dir.stat.exists == false

- name: Copy DetectionLab folder to target machine
  win_copy: src=../../../DetectionLab/ dest=C:\DetectionLab\


- name: Copy scripts to c:\vagrant
  win_shell: Copy-Item -Force -Recurse c:\DetectionLab\Vagrant c:\vagrant

- name: Join the Domain
  win_shell: .\\provision.ps1
  args:
    chdir: 'c:\vagrant\scripts'
  register: wef_join_domain
  changed_when: "'HasSucceeded : True' in wef_join_domain.stdout"

- debug: msg="{{ wef_join_domain.stdout_lines }}"

- name: Reboot After Joining the Domain
  win_reboot:
    msg: "Joining the domain. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60

- name: Clear Event Logs
  win_shell: "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"
